### ISSUE TITLE
cuadro comparativo gil velasco

### ISSUE THREAD

**Issue by gilbertovelasco1** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-gilbertovelasco1#1]
[cuadro comparativo sprit 2 gilberto velasco osorio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-gilbertovelasco1/files/9649342/cuadro.comparativo.sprit.2.gilberto.velasco.osorio.pdf)

**Comment by josealfredo79** [comment]
Calificación 16

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
